version: '3.9'

services:
  web:
    container_name: wozzby_app
    image: wozzby_app
    restart: unless-stopped
    build:
      target: web
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres_db
    networks:
      - app-network

  postgres_db:
    image: postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - "./postgres_db:/var/lib/postgresql/data"
    networks:
      - app-network

  phppgadmin:
    image: dockage/phppgadmin
    container_name: phppgadmin
    restart: unless-stopped
    depends_on:
      - postgres_db
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PHP_PG_ADMIN_SERVER_DESC: PostgreSQL
      PHP_PG_ADMIN_SERVER_HOST: postgres_db
      PHP_PG_ADMIN_SERVER_PORT: ${DB_PORT}
      PHP_PG_ADMIN_SERVER_SSL_MODE: allow
      PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY: true
    networks:
      - app-network

volumes:
  postgres_db:

networks:
  app-network:
    driver: bridge
